In [2]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
# 如果没有安装pandas，只需取消对以下行的注释来安装pandas
# !pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [5]:
type(data)

pandas.core.frame.DataFrame

In [7]:
# iloc()的意思是根据位置编号取数据，而不是根据标签
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN


In [8]:
print(outputs)

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


In [ ]:
# 用同一列的均值填充
# 内部逻辑是，遍历每一列，如果是数值列就计算mean，返回一个series
# 同样遍历每一列，如果在series里面找到了这一列的key，就填充mean
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [ ]:
# 处理Alley（巷子）属性，分成两个属性，独热编码
# get_dummies()遍历所有列，数值列不处理，离散列需要编码
# 找到该列的所有唯一值，因为设置了dummy_na=True，所以NaN也被识别成一种
# 为每个类别创建新列，Alley_Pave, Alley_NaN
# 逐行比较，进行独热编码
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [12]:
type(inputs)

pandas.core.frame.DataFrame

In [15]:
inputs.to_numpy(dtype=float)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [16]:
type(inputs)

pandas.core.frame.DataFrame

In [17]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
X

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [18]:
y = torch.tensor(outputs.to_numpy(dtype=float))
y

tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

In [2]:
x + y, x - y, x / y, x * y

(tensor(5.), tensor(1.), tensor(1.5000), tensor(6.))

In [3]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
x[3]

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape

torch.Size([4])

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B = torch.tensor([[1 ,2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [14]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [15]:
A + B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [17]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [18]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [20]:
(a * X).shape

torch.Size([2, 3, 4])

In [21]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [22]:
x.sum()

tensor(6.)

In [23]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [24]:
A.shape

torch.Size([5, 4])

In [25]:
A.sum()

tensor(190.)

In [26]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0

tensor([40., 45., 50., 55.])

In [27]:
A_sum_axis0.shape

torch.Size([4])

In [28]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

tensor([ 6., 22., 38., 54., 70.])

In [29]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [30]:
A.mean()

tensor(9.5000)

In [31]:
A.numel()

20

In [32]:
A.sum() / A.numel()

tensor(9.5000)

In [33]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [34]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [35]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [36]:
y = torch.ones(4, dtype=torch.float32)
y

tensor([1., 1., 1., 1.])

In [37]:
x

tensor([0., 1., 2., 3.])

In [38]:
torch.dot(x, y)

tensor(6.)

In [39]:
A.shape

torch.Size([5, 4])

In [40]:
x.shape

torch.Size([4])

In [41]:
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [42]:
u = torch.tensor([3.0, -4.0])
u

tensor([ 3., -4.])

In [43]:
torch.norm(u)

tensor(5.)

In [44]:
torch.abs(u).sum()

tensor(7.)

In [45]:
torch.ones(4, 9)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
torch.norm(torch.ones(4, 9))

tensor(6.)

In [50]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [52]:
x.requires_grad_(True)
print(x.grad)

None


In [53]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [54]:
y.backward()

In [55]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [56]:
x.grad == 4 * x

tensor([True, True, True, True])

In [57]:
x.grad.zero_()
print(x.grad)

tensor([0., 0., 0., 0.])


In [58]:
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])