In [2]:
# 张量tensor，一维就是向量，二维就是矩阵
import torch

In [3]:
# arange创建一个行向量，每个值叫做张量的元素
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# shape访问张量沿每个轴的长度
x.shape

torch.Size([12])

In [5]:
# numel访问张量中元素的总数
x.numel()

12

In [6]:
# reshape改变张量的形状而不改变数量和元素值
# 也就是reshape之后张量元素的总数不变
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
X.shape

torch.Size([3, 4])

In [8]:
# 不需要知道每个维度的具体值也可以改变向量
# 通过-1来调用自动计算维度的功能
Y = x.reshape(3, -1)
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
# zeros可以让张量的全部元素为0
# 理解为有2个3行4列的矩阵
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# ones可以让张量的元素都为1
# 这两个函数都要求输入是一个tuple，表示张量的维度
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
# randn可以让张量的每个元素都从正态分布里面采样
torch.randn(3, 4)

tensor([[-1.5182, -0.4917,  1.0598, -0.3525],
        [-0.5515, -0.6354,  2.0574, -0.5761],
        [ 0.0086, -1.2632, -0.8151,  1.6623]])

In [12]:
# 也可以用列表来创建向量
torch.tensor([
    [2, 1, 4, 3],
    [1, 2, 3, 4],
    [5, 4, 1, 0],
    [1, 4, 4, 1]
])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [5, 4, 1, 0],
        [1, 4, 4, 1]])

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
x

tensor([1., 2., 4., 8.])

In [14]:
y = torch.tensor([2, 2, 2, 2])
y

tensor([2, 2, 2, 2])

In [15]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [16]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [17]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [18]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [19]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [20]:
# 对张量x中的每个元素逐个取指数函数
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [21]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
Y = torch.tensor([
    [2.0, 1, 4, 3], 
    [1, 2, 3, 4], 
    [4, 3, 2, 1]
])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [23]:
# dim=0按照第一个维度连接，形状的第一个元素3+3=6
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [24]:
# dim=1按照第二个维度连接，形状的第二个元素4+4=8
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [25]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
X.sum()

tensor(66.)

In [27]:
# 广播机制：即使形状不相同，也可以执行按元素操作
# 通过适当复制元素来扩展一个或两个数组，以便在转换后两个张量具有相同的形状
# 对生成的数组执行按元素操作
a = torch.arange(3).reshape((3, 1))
a

tensor([[0],
        [1],
        [2]])

In [28]:
b = torch.arange(2).reshape((1, 2))
b

tensor([[0, 1]])

In [29]:
# a复制列，b复制行
# 0 0   0 1   0 1
# 1 1 + 0 1 = 1 2
# 2 2   0 1   2 3
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [32]:
# 索引和切片
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [33]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [34]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# 前两行和全部列
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# id()提供内存中引用对象的确切地址
before = id(Y)
Y = Y + X
# Python首先计算Y+X，为这个结果分配新的内存，让Y指向内存中的这个新位置
before == id(Y)

False

In [ ]:
# zeros_like()是按照已有的张量规格生成一个全0的张量
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
# 通过对张量的切片表示将操作的结果分配给之前的张量，就是不用额外开辟内存
Z[:] = X + Y
print("id(Z):", id(Z))

id(Z): 2339272223024
id(Z): 2339272223024


In [43]:
before = id(X)
X += Y
id(X) == before

True

In [45]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [46]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)